### ISSUE TITLE
Empty `table` property in cloud request for standalone checks causes cloud integration to fail

### ISSUE THREAD

**Issue by m1n0** [sodadata/soda-core#1161]
Soda Cloud does not support check results without `table` property. This property is filled with `checks for X` and is not present in "standalone" checks with no table property e.g. 
```
checks:
  ....
```

Options:
1. Disallow checks without table association 
This seems very suboptimal as such checks have been identified as useful

2. Detect a table from the checks automatically
Seems unreliable and too much work

3. Change cloud to accept checks with no table.
This is technically easy, but more challenging from product point of view - the UI would have to deal with such checks appropriately.

**Comment by tombaeyens** [comment]
@m1n0 Can you elaborate what you mean here?

**Comment by m1n0** [comment]
@tombaeyens I updated the title and description with proper context.

**Comment by vijaykiran** [comment]
I don't think this is severe enough that warrants extra work.
