### ISSUE TITLE
Datasets page - UI formatting issue with long dataset names (Safari)

### ISSUE THREAD

**Issue by jasonicarter** [sodadata/soda-core#1163]
The UI Datasets page, https://cloud.soda.io/datasets/overview,  doesn't format well for long `dataset` names (full screen)

<img width="533" alt="image" src="https://user-images.githubusercontent.com/5205478/159817455-2be158c0-b69d-41a8-b404-1b3301548b0e.png">

Safari
- Version 15.3 (17612.4.9.1.8)

**Comment by dirkgroenen** [comment]
Thanks for filing this issue @jasonicarter. I've opened an issue on the internal backlog of the Soda Cloud team so we can take a look at this! :pray:

**Comment by dirkgroenen** [comment]
This has been resolved by the Cloud Team last week.
