### ISSUE TITLE
Valid format dates backwards

### ISSUE THREAD

**Issue by janet-can** [sodadata/soda-core#1171]
These valid formats backwards in `soda/sodacl/format_cfg.py`.  date eu should be DD/MM/YY and date us should be MM/DD/YY.

```
            "date eu": rf"^{s}{month}[-\./]{day}[-\./]{year}{s}$",
            "date us": rf"^{s}{day}[-\./]{month}[-\./]{year}{s}$",
```

**Comment by tombaeyens** [comment]
To be checked, this might already be fixed.
