### ISSUE TITLE
CLI returns 0 even when failures

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-core#1213]
Only failures should return 1, warnings should still produce 0

**Comment by tombaeyens** [comment]
| warnings | failures | errors |  exit code |
| --------- | ------- | ------ | ---------- |
| no | no | no | 0 |
| yes | no | no | 1 |
| * | yes | no | 2 |
| * | * | yes | 3 |

**Comment by m1n0** [comment]
@tombaeyens returning 1 in case of warnings seems to introduce another issue - when soda-core is used in a pipeline and it returns 1 in case of warnings - this will stop tie pipeline etc. What are your thoughts on this?
