### ISSUE TITLE
Anomaly detection

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-core#1217]
TODO replace this with a proper description : That answers questions like

* What is already completed and what still needs to be done
* What metrics will be supported
* What does the language look like
* What are the limitations
* How will it be linked to the scientific extension

We should be able to produce an estimate on all the work still to be done

**Comment by tombaeyens** [comment]
Merged @bastienboutonnet issue #1224 in here:

> add/migrate anomaly check unit tests
> might have to wait until we're 100% sure of the data contracts between core and sci package.

**Comment by vijaykiran** [comment]
Done.
