### ISSUE TITLE
rework documentation for distribution checks

### ISSUE THREAD

**Issue by bastienboutonnet** [sodadata/soda-core#1223]
- add mention of sci package on the general readme.
- rework docs.soda.io page with installation pre-requisites

**Comment by tombaeyens** [comment]
How do you want to present this docs installation pre-requisites?  My proposal is to update the getting started https://docs.soda.io/soda-core/get-started.html

And ensure this is explained properly:

* soda core includes scan capability and all cli
* data source modules extend soda core with support for a specific data source type
* scientific package extends soda core with scientific capabilities 

Does that make sense?

**Comment by bastienboutonnet** [comment]
Yeah there's probably something to add to the general getting started entry point.

I also need to add some guidelines on data size etc. This ticket is currently a placeholder for planning, needs to be groomed but your input above makes sense, I'll be adding that to the scope of this rework.

Right now, https://docs.soda.io/soda-cl/distribution.html does not even have a mention of pre-requisites etc. as we wrote it a bit in a haste.

**Comment by vijaykiran** [comment]
@bastienboutonnet  Can this issue can be closed ?

**Comment by bastienboutonnet** [comment]
Yes
