### ISSUE TITLE
add/migrate anomaly check unit tests

### ISSUE THREAD

**Issue by bastienboutonnet** [sodadata/soda-core#1224]
might have to wait until we're 100% sure of the data contracts between core and sci package.

**Comment by tombaeyens** [comment]
@bastienboutonnet Can you elaborate a bit on what's needs to be decided / analyzed in terms of the data contract?  Or on which other issue it depends?  and what this issue then would entail?

**Comment by tombaeyens** [comment]
Merged into #1217
