### ISSUE TITLE
Propose distribution checks cloud integration

### ISSUE THREAD

**Issue by bastienboutonnet** [sodadata/soda-core#1226]
Some high-level considerations:
- DRO cloud storage
- visualisation in cloud

**Comment by tombaeyens** [comment]
@bastienboutonnet Can you sketch the difference between what we have now and what the DRO cloud storage would bring?  That will make it easier for @mathissedestrooper and Benjamin to evaluate this feature.  As I'm not sure we need to prioritize the DRO cloud storage.  I think it justifies to build a feature spec that also includes what work is needed in Soda Core and what needs to be done in Soda Cloud in more detail.  Does that make sense?

**Comment by bastienboutonnet** [comment]
@tombaeyens of course, this is a placeholder, I'll be fleshing this out in due time it's not a priority for now. It is something that will probably get more attention towards the end of Q2 as per roadmap discussions with @mathissedestrooper. For now, no need to worry about it.

**Comment by vijaykiran** [comment]
@bastienboutonnet Is this still open or can be moved into JIRA ?

**Comment by bastienboutonnet** [comment]
Moved to Jira.
