### ISSUE TITLE
Profiling advanced

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-core#1239]
This is the configuration that is going to be used by Soda Cloud to populate the EDA view.

It will tell Soda Core to extract samples and compute the detailed statistics per column like min, max, frequent values, histograms etc.

```
profiling advanced:
  tables:
    - SODATEST_%
    - include SODATEST_%
    - exclude SODATEST_%
  columns:
    - TABLE%.COLNAME%
    - include TABLE%.COLNAME%
    - exclude TABLE%.COLNAME%
  max sample size: 100
  statistics: enabled  
```

**Comment by bastienboutonnet** [comment]
Original issue: https://github.com/sodadata/soda-sql-v3/issues/250

**Comment by bastienboutonnet** [comment]
@tombaeyens what does `statistics` stand for/control in this proposal?

**Comment by bastienboutonnet** [comment]
Closed in favour of: https://github.com/sodadata/soda-core/issues/1256
