### ISSUE TITLE
Implement profiling/EDA metrics

### ISSUE THREAD

**Issue by bastienboutonnet** [sodadata/soda-core#1258]
soda-sql offered the following profiling metrics to be pushed into the EDA views of Soda Cloud:
- [ ] count
  - [x] numeric columns:
    - [x] min
    - [x] max
    - [x] avg
    - [x] stddev
    - [x] variance
    - [x] frequent values
    - [x] histograms
    - [x] sum
    - [x] min 5 values
    - [x] max 5 values
    - [x] distinct values
    - [x] missing values
  - [ ] text columns:
    - [x] frequent_values
    - [ ] min length
    - [ ] max length
    - [ ] avg length 

These metrics all need to be re-implemented in soda-core this means:
- fit into the new metrics objects
- be able to generate the right queries for each supported dialect

**Comment by bastienboutonnet** [comment]
More info and links to cloud DTOs can also be found in this closed issue: https://github.com/sodadata/soda-sql-v3/issues/250

**Comment by bastienboutonnet** [comment]
In soda cloud, I see that text columns have the "Extreme Values" tab enabled. However, for text columns, I don't really see how that makes sense on text columns.

@tombaeyens @dirkgroenen do you have an idea why that is?

**Comment by tombaeyens** [comment]
@bastienboutonnet I think this is a duplicate of https://github.com/sodadata/soda-core/issues/1256

Can you close this one if you agree or make a comment if you think otherwise?

**Comment by bastienboutonnet** [comment]
Implemented
