### ISSUE TITLE
Provide error when `set_scan_definition_name` is not set but SodaCloud config is set

### ISSUE THREAD

**Issue by jasonicarter** [sodadata/soda-core#1261]
When programmatically triggering scans, you are required to set the scan definition name ONLY if you are sending data to SodaCloud. However, if you do have SodaCloud configured and do not `set_scan_definition_name` you receive no error message and it completes "successfully" without sending data to Soda Cloud.

https://github.com/sodadata/soda-core/blob/main/soda/core/soda/scan.py#L56

```python
from soda.scan import Scan
scan = Scan()
scan.set_scan_definition_name("my_def_name")
...
scan.execute()
```
Documentation didn't mention this either.

**Comment by vijaykiran** [comment]
This is fixed via https://github.com/sodadata/soda-core/blob/main/soda/core/soda/scan.py#L352
