### ISSUE TITLE
Freshness does not work with date datatype

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#1275]
Freshness does not work with a date datatype.

**Comment by jrsalazar14** [comment]
Getting this Error log as well,
`Could not evaluate freshness: max(PARTITION_DATE) is not a datetime: date

Freshness Check [NOT EVALUATED]
INFO   |         max_column_timestamp: 2022-08-10
INFO   |         max_column_timestamp_utc: None
INFO   |         now_variable_name: NOW
INFO   |         now_timestamp: 2022-08-10T22:58:08.875657+00:00
INFO   |         now_timestamp_utc: 2022-08-10 22:58:08.875657+00:00
INFO   |         freshness: None`

**Comment by janet-can** [comment]
Adding another +1 from a new user who would wish to use a column with just `date` to check for freshness.

**Comment by geertjan-garvis** [comment]
Adding a +1 as well, we bump into this in several places

**Comment by janet-can** [comment]
https://sodadata.atlassian.net/browse/CORE-335

**Comment by vijaykiran** [comment]
Closed by #1667

**Comment by geertjan-garvis** [comment]
> Closed by #1667

Fantastic, thank you Vijay!

**Comment by janet-can** [comment]
@geertjan-garvis - merged but not yet released!  Just FYI :)

**Comment by geertjan-garvis** [comment]
@janet-can - understood :-)
