### ISSUE TITLE
`matplotlib` logger level is elevated when importing `ProphetDetector`

### ISSUE THREAD

**Issue by bastienboutonnet** [sodadata/soda-core#1288]
When importing `ProphetDetector` from https://github.com/sodadata/soda-core/blob/40d00724dbb44f3da557412bdba12620898124ee/soda/scientific/soda/scientific/anomaly_detection/models/prophet_model.py

`matplotlib` is imported but it has a very verbose log level which causes it to print a LOT of useless stuff such as the list of installed packages and various paths.

My current workaround is to set the level of `matplotlib` logger right before importing prophet (https://github.com/sodadata/soda-core/blob/40d00724dbb44f3da557412bdba12620898124ee/soda/scientific/soda/scientific/anomaly_detection/models/prophet_model.py#L4)

We might have a better place in soda-core to do that.

**Comment by m1n0** [comment]
This is now done in [proper place](https://github.com/sodadata/soda-core/blob/eb01e6014669ba240db96226cca48e4c6bbe0ff8/soda/core/soda/common/logs.py#L18) where logging is handled so we can probably close this one correct?

**Comment by m1n0** [comment]
closing, please reopen if something still needs to be done.
