### ISSUE TITLE
Test packaging of soda-scientific with anomaly detection to make sure it installs for most systems

### ISSUE THREAD

**Issue by bastienboutonnet** [sodadata/soda-core#1289]
@vijaykiran was having issues installing the `soda-scientific` package when `prophet` is in the requirements.

I do not...

We will need to survey on a bunch of machines internally what people run into and find a way to make sure we can package it and fix installations issues as much as possible, or at least have a good idea of the issues that people may run into so we can support them.

**Comment by vijaykiran** [comment]
Looks like this is solved with removal of pystan dep from prophet
