### ISSUE TITLE
push a docker image for soda-core as part of the build process

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-core#1299]
Publish to https://hub.docker.com/r/sodadata/soda-core

**Comment by vijaykiran** [comment]
@m1n0  can you push the image today to unblock @albinkjellin ?

**Comment by m1n0** [comment]
https://hub.docker.com/r/sodadata/soda-core is now up to date with latest docker image, it should always have the latest built from main and tag from tags.
