### ISSUE TITLE
`soda_core_uploads_disabled` should not count as an error

### ISSUE THREAD

**Issue by jasonicarter** [sodadata/soda-core#1347]
A failed check attempted to send data to Soda Cloud but I have disabled sending sample data. This resulted in `3 Errors` but as I disabled this feature, it shouldn't be counted (or reported) as an error

```bash
Soda Core 3.0.0b12
> /api/command (login with API key credentials)
< 200 (login ok, token received)
Empty file upload detected, not sending Content-Length header
No fileId received in response: {'code': 'soda_core_uploads_disabled', 'message': 'File uploads disabled by administrator'}
Soda cloud error: Could not upload sample <table_name>_failed_rows
  | 'fileId'
Empty file upload detected, not sending Content-Length header
No fileId received in response: {'code': 'soda_core_uploads_disabled', 'message': 'File uploads disabled by administrator'}
Soda cloud error: Could not upload sample failed_rows
  | 'fileId'
No fileId received in response: {'code': 'soda_core_uploads_disabled', 'message': 'File uploads disabled by administrator'}
Soda cloud error: Could not upload sample failed_rows
  | 'fileId'
Scan summary:

[...]

ERRORS:
Soda cloud error: Could not upload sample <table_name>_failed_rows
  | 'fileId'
Soda cloud error: Could not upload sample failed_rows
  | 'fileId'
Soda cloud error: Could not upload sample failed_rows
  | 'fileId'
Sending results to Soda Cloud
```

When viewing the exit code I get `3` which I assume is custom to prevent/catch types of failures...
```bash
[...]/soda-cl# echo $?
3
```

**Comment by tombaeyens** [comment]
Thanks for reporting, Jason!

I planned to add that tomorrow.  ..and didn't realize this was going to bite anyone.  You're running from main  or were you runing from pypi?

**Comment by tombaeyens** [comment]
Can you confirm that you don't have key `soda_cloud:` in your configuration yaml?

**Comment by tombaeyens** [comment]
removing the `soda_cloud:` config would fix it but i guess that is not what you want.

ok got it.  in that case we ll roll out a fix release in the coming days for this.

**Comment by jmarien** [comment]
SODA-467

**Comment by tombaeyens** [comment]
@vijaykiran can you let @jasonicarter know when he can expect a new release to be published?
