### ISSUE TITLE
Expand to fully qualified table name in Failed rows check with fail query

### ISSUE THREAD

**Issue by m1n0** [sodadata/soda-core#1364]
```
checks:
    - failed rows:
        name: Customers must have size
        fail query: |
            SELECT *
            FROM customers
            WHERE size < 0
```
this runs the query as is, but if data source requires fully qualified name, e.g. including schema, then the check might not work (looking at you Athena).

Suggestion: parse the fail query and expand the table name to whatever it needs to be. 
Critical? No
Workaround - specify fully qualified table name in the check 🤷

**Comment by jmarien** [comment]
SODA-545

**Comment by m1n0** [comment]
this is obsolete and was solved on a connector level with default db/schema
