### ISSUE TITLE
Checks that depend on the scientific library should first assert that module is installed

### ISSUE THREAD

**Issue by bastienboutonnet** [sodadata/soda-core#1369]
Rather than letting the evaluation fail with something like a `ModuleNotFoundError` we probably should make sure we have some logic that we can re-use for all checks that depend on the scientific library that explicitly checks whether the module is installed and throws a proper log and potentially a link to the docs on how to install the module so that users do not have to parse the `ModuleNotFoundError` for themselves.

**Comment by jmarien** [comment]
SODA-550
