### ISSUE TITLE
Creating repeated checks in SodaCL by iterating over some defined values within a table

### ISSUE THREAD

**Issue by pwrignall** [sodadata/soda-core#1417]
The aim of this would be to achieve something like the following, but using only SodaCL:

```
def soda_scan(query):
    # do stuff

# uid: threshold_value
input_dict = {"1043": "50",
              "1098": "55",
              "934": "50",
              "755": "60"
              }

for k, v in input_dict.items():
    failed_rows_query = f"select * from some_table where uid = {k} and some_col > {v}"
    soda_scan(failed_rows_query)
```

If such a construct could be implemented, it'd also be great to use those values that are iterated over in the check name, something like `name: Max value for uid {k} was over the specified threshold of {v}!`

**Comment by jmarien** [comment]
SODA-890

**Comment by m1n0** [comment]
This can be achieved in multiple ways depending on use case:
- `for each` in sodacl
- Jinja templating
- programatic scan
Closing as this is not a priority at the moment.
