### ISSUE TITLE
soda-core-bigquery 3.0.0rc2 has compatibility issues with Astronomer

### ISSUE THREAD

**Issue by kamalacharya** [sodadata/soda-core#1450]
While trying to install the 3.0.0rc2 version of soda-core-bigquery on our astronomer (airflow) docker image we run into package version conflict. Below are logs from the build.

> ERROR: Cannot install google-ads==16.0.0, google-api-core[grpc]==2.8.1, google-cloud-bigquery-storage and soda-core-bigquery because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     google-api-core[grpc] 2.8.1 depends on protobuf<4.0.0dev and >=3.15.0
>     proto-plus 1.19.6 depends on protobuf>=3.12.0
>     soda-core 3.0.0rc2 depends on protobuf~=3.19.0
>     google-cloud-bigquery 2.34.3 depends on protobuf>=3.12.0
>     google-ads 16.0.0 depends on protobuf!=3.18.*, !=3.19.*, <=3.20.0 and >=3.12.0
>     The user requested (constraint) protobuf==3.19.0

**Comment by jmarien** [comment]
SODA-915

**Comment by vijaykiran** [comment]
@kamalacharya  Can you please check with the latest version and let us know if you still have an issue?
