### ISSUE TITLE
Support for Snowflake tokens

### ISSUE THREAD

**Issue by adam-wrobel** [sodadata/soda-core#1471]
Please enable auth via token, which looks like this in a regular connector:

```python
ctx = snowflake.connector.connect(
                                      account='my account',
                                      authenticator='oauth',
                                      token=access_token,                          # Generated via corporate SSO
                                      warehouse="my warehouse",
                                      database="my db", role="my role")
```

**Comment by jmarien** [comment]
SODA-944

**Comment by vijaykiran** [comment]
docs from snowflake connector: https://docs.snowflake.com/en/user-guide/python-connector-example.html#connecting-with-oauth

**Comment by vijaykiran** [comment]
Hey @adam-wrobel  would you like to fix it via PR  by updating https://github.com/sodadata/soda-core/blob/main/soda/snowflake/soda/data_sources/snowflake_data_source.py#L74 ?

**Comment by adam-wrobel** [comment]
@vijaykiran  I can give it a try. WIll check it locally first

**Comment by Adamage** [comment]
will close issue after next release if thats ok
