### ISSUE TITLE
Override scan data/time

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#1493]
It would be great to have an option to override the data time section of when the scan is performed in order to look at historic data. Like -t in Soda SQL.

**Comment by jmarien** [comment]
SODA-972

**Comment by janet-can** [comment]
I do believe this is complete and merged... @albinkjellin Ok to close?

**Comment by vijaykiran** [comment]
there is an option to use `-t` or `--data-timestamp`
