### ISSUE TITLE
Missing values not working when filter is required over a bigquery table

### ISSUE THREAD

**Issue by alanplarium** [sodadata/soda-core#1506]
I have a yaml file: 

```
filter spend_pocsodacore [daily]:
  where: day = CURRENT_DATE()-3

checks for spend_pocsodacore [daily]:
  - missing_percent(my_column):
      missing values: [7]
      warn: when < 5% 
      name: Missing percentage of my_column
```

7 is a value on my_column, that i wanna treat it as missing value. The percentage of rows having 7 is 22%
When running the scan it fails because:
Cannot query over table 'spend_pocsodacore' without a filter over column(s) 'day'
I see there is a generated query

```
SELECT * 
FROM spend_pocsodacore 
WHERE day = CURRENT_DATE()-3 AND my_column IS NULL OR my_column IN (7)
```

there should be a ( after the AND

**Comment by jmarien** [comment]
SODA-995

**Comment by m1n0** [comment]
hi @alanplarium, thanks for reporting the issue, coming back to this one:
using your check file the query should be in the format 
```
SELECT
  COUNT(*),
  COUNT(CASE WHEN my_column IS NULL OR my_column IN (7) THEN 1 END)
FROM test.spend_pocsodacore
WHERE day = CURRENT_DATE()-3
```

What version of soda-core were you using when encountering the issue please? The query above should be run when using the provided check config, and the query does look correct to me.

**Comment by alanplarium** [comment]
@m1n0 As I see in the history of run queries in bigquery there are two queries that run. The one you posted and the one I posted. Yours run first then mine. Mine is the one that fails.
The version of soda core I am using is v3.0.2

**Comment by vijaykiran** [comment]
@alanplarium  can you please test with 3.0.12 and reopen if it doesn't work?
