### ISSUE TITLE
[snowflake] queries on information schema are painfully slow

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-core#1511]
Looks like metadata queries on snowflake are very slow if we use `lower` on columns and table names.

See: https://stackoverflow.com/a/65078113/440589
and https://community.snowflake.com/s/article/metadata-operations-throttling#:%7E:text=What%20are%20the%20Metadata%20Operations,warehouse%20or%20customer%20data%20storage

Review the places in Snowflake data source and update the queries to more performant versions.

thank you @jasonicarter for help in debugging this issue!

**Comment by jmarien** [comment]
SODA-1000

**Comment by vijaykiran** [comment]
Fixed in 3.0.11
