### ISSUE TITLE
Same Dataset Name in Different Schemas not showing scans information on the SODA CLOUD

### ISSUE THREAD

**Issue by sutaraj01** [sodadata/soda-core#1542]
Soda Version v3.0.3
Snowflake Datasource

While performing scans on two datasets which has the exact same name and checks definition but in the different schema the scan results are not showing up in the Soda Cloud for one of the datasets. Often it is flipping between both of them it seems.

Please see my example below.

Checks for Dataset 1
```
checks for UNIT_MARGIN_V:
  - freshness(res_date, CUST_VAR):
      warn: when > 240m
      fail: when > 300m
      name: Freshness for DATASCIENCE.UNIT_MARGIN_V warn when >240m and Fail >300m
  - schema:
      name: Any schema changes
      warn: 
        when schema changes:
          - column add
          - column index change
          - column type change
      fail:
        when schema changes: 
         - column delete
```

Checks for Dataset 2
```
checks for UNIT_MARGIN_V:
  - freshness(res_date, CUST_VAR):
      warn: when > 240m
      fail: when > 300m
      name: Freshness for UMR.UNIT_MARGIN_V warn when >240m and Fail >300m
  - schema:
      name: Any schema changes
      warn: 
        when schema changes:
          - column add
          - column index change
          - column type change
      fail:
        when schema changes: 
         - column delete
```

![image](https://user-images.githubusercontent.com/15704934/184638651-e9e344d5-7c24-4a90-91d9-495b3221ceff.png)
![image](https://user-images.githubusercontent.com/15704934/184638674-2ae75158-b845-467c-97be-6ba078548a6b.png)
![image](https://user-images.githubusercontent.com/15704934/184639257-5dfd49f3-3f33-4876-abf8-790590e5a43e.png)
![image](https://user-images.githubusercontent.com/15704934/184638931-37b55d92-f0b9-408b-9314-92068f353281.png)
![image](https://user-images.githubusercontent.com/15704934/184638992-3972c5da-ccd7-425a-af96-cdd7dac51f54.png)

**Comment by dirkgroenen** [comment]
Thanks @sutaraj01 - we're currently also tracking this on our internal cloud backlog. It's not a problem the Core team can resolve so I'll close this for now and keep you posted of any further updates. 👍
