### ISSUE TITLE
SodaCL: A failed regex check causes a SELECT * query which fails due to data size

### ISSUE THREAD

**Issue by Simon-King-HV** [sodadata/soda-core#1548]
Using open source SodaCL against Databricks data frames

Running an invalid_count check with a valid regex definition causes a SELECT * after the initial test. This second query fails due to the breadth and size of the table. 100 columns and 31M rows.

I am not interested in the sampling of failed rows. Need a way to suppress this second query.

INFO   | Soda Core 3.0.4
DEBUG  | Scan execution starts
DEBUG  | Query test_df.test_df.aggregation[0]:
SELECT
  COUNT(CASE WHEN NOT (ds2_admin_date IS NULL) AND NOT (ds2_admin_date rlike(’^\\d4-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$‘)) THEN 1 END)
FROM test_df
DEBUG  | Query test_df.ds2_admin_date.failed_rows[invalid_count]:
SELECT *
FROM test_df
WHERE NOT ds2_admin_date IS NULL AND NOT ds2_admin_date rlike(’^\\d4-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$‘)
ERROR  | Query error: test_df.ds2_admin_date.failed_rows[invalid_count]: An error occurred while calling o1256.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Total size of serialized results of 10 tasks (4.1 GiB) is bigger than spark.driver.maxResultSize 4.0 GiB.

Running a check which passes 
INFO   | Soda Core 3.0.4
DEBUG  | Scan execution starts
DEBUG  | Query test_df.test_df.aggregation[0]:
SELECT
  COUNT(*)
FROM test_df
INFO   | Scan summary:
DEBUG  | 1/1 query OK
DEBUG  |   test_df.test_df.aggregation[0] [OK] 0:04:14.024403
INFO   | 1/1 check PASSED:
INFO   |     test_df in test_df
INFO   |       row_count > 1 [PASSED]
INFO   |         check_value: 31618722
INFO   | All is good. No failures. No warnings. No errors.

**Comment by Simon-King-HV** [comment]
Adding scan._configuration.sampler = None seems to resolve the issue in the short term

**Comment by Simon-King-HV** [comment]
Update - while setting scan._configuration.samples = None works for the simple COUNT() measures, it causes any failed rows or reference check between tables to fail with issues referencing the None value. So this is only a partial workaround.

**Comment by m1n0** [comment]
numeric and duplicate checks have been refactored to work much better with large data sets, reference checks are in our backlog to be refactored as well.
