### ISSUE TITLE
Anomaly score check not evaluating after >4 scans

### ISSUE THREAD

**Issue by janet-can** [sodadata/soda-core#1558]
The expectation is that an anomaly score check begins evaluating after a minimum of four, regular-frequency scans that gathered measurements. However, after multiple regularly-scheduled hourly scans of a dataset, the anomaly score check is still not evaluation. 

- Why does it not show the "Last scan ended" value? The duration value in the other view attests to the fact that the scan did complete.
- The Scan success results are puzzling-- what does the value 11.54 for the Anomaly test indicate?

Ultimately, just can't get the anomaly score to yield expected output and we're not sure why. 
![Screen Shot 2022-08-26 at 11 22 17](https://user-images.githubusercontent.com/63879030/186975356-5fe8e7e0-c675-42be-b5bd-c03d9a4f6778.png)
![Screen Shot 2022-08-26 at 11 22 27](https://user-images.githubusercontent.com/63879030/186975360-6ae1f671-4d1f-4859-8845-f236fd30cf12.png)
![Screen Shot 2022-08-26 at 11 23 17](https://user-images.githubusercontent.com/63879030/186975362-b7a9fb4e-c341-4dba-a7a1-8ed064601f04.png)
![Screen Shot 2022-08-26 at 11 24 45](https://user-images.githubusercontent.com/63879030/186975369-b2e88f0d-f1d4-4be7-827f-5eef658c427f.png)

**Comment by vijaykiran** [comment]
@janet-can  is it still an issue ? If so can you please open in JIRA?

**Comment by janet-can** [comment]
I'm not sure-- this one came from Zefr as an issue. I'll check back with Jose and if it's still an issue, I'll create a Jira.
