### ISSUE TITLE
Allow validity check to specify invalid regex to match against

### ISSUE THREAD

**Issue by Simon-King-HV** [sodadata/soda-core#1560]
As a tester I would like to specify the regex to match invalid values in a column rather than being limited to only specify valid values and have the measure count those rows with values failing the match.

We have a cleansing process to remove private coded values. These are limited and anything that does match the privacy values is considered valid.

I would like to be able to code a test as:
- invalid_count(column_name) = 0:
      invalid regex: .....

Today I would have to create the inverse regex and use the "valid regex:" condition. Given the high number of valid codes vs. invalid code this is too burdensome. I could also use the "failed rows" test, however, that attempts to pull back the rows for all failures and given that I have a multi-billion row table this will blow up my Databricks dataframe and notebook. I need the simpler approach where Soda will attempt to count matching failed values.

Suggestion: Could this be as simple as changing the RLIKE <regex> to NOT RLIKE <regex> depending upon the "valid regex" or "invalid regex" used?

**Comment by m1n0** [comment]
Both valid and invalid format/regex/ are supported now
