### ISSUE TITLE
Enhancement to allow failed rows tests to simply count and not return full rows

### ISSUE THREAD

**Issue by Simon-King-HV** [sodadata/soda-core#1563]
As a tester I would like to submit a SQL query or complex CTE to test.

This could be a change to the failed rows test to allow just a count of the failing rows to be tested, or it could be an enhancement to the invalid_count, invalid_percent, etc. to allow a more complex SQL/CTE to be provided.

Currently if I use the failed rows this performs a SELECT * on the query and as a result my databricks dataframe is overloaded when I run this against a very large table. A SELECT COUNT(*) on the same query would result in a manageable query result to be tested.

**Comment by vijaykiran** [comment]
This can be done by setting samples limit to 0.

**Comment by Simon-King-HV** [comment]
And how does one do that?
