### ISSUE TITLE
Soda-Core Clickhouse Support

### ISSUE THREAD

**Issue by vargacypher** [sodadata/soda-core#1593]
Hi guys,

Today Clickhouse it's our main DW and we would appreciate a lot if Soda-Core could integrate with it.
https://clickhouse.com/

Someone know if there is a way ?

**Comment by jmarien** [comment]
SODA-1182

**Comment by vijaykiran** [comment]
@vargacypher  We don't have direct support for it yet - but AFAIK, Clickhouse has MySQL wire protocol compatibility, maybe you can try using the `soda-core-mysql` package? Not sure how far you can go with it though

**Comment by vargacypher** [comment]
Oh Thk's, 
I will test and give you feedback

**Comment by vargacypher** [comment]
Sorry about that, i was using the wrong port (9000 clickhouse native), when i changed to 9004 ( present in config.xml https://clickhouse.com/docs/en/interfaces/mysql/ ) **it works** .
![image](https://user-images.githubusercontent.com/77084039/193825924-78130de7-4007-41db-b7ce-4335aea9b27c.png)

**Comment by vijaykiran** [comment]
@vargacypher Thank you for the feedback 🙏

**Comment by mrkoloev** [comment]
> Sorry about that, i was using the wrong port (9000 clickhouse native), when i changed to 9004 ( present in config.xml https://clickhouse.com/docs/en/interfaces/mysql/ ) **it works** . ![image](https://user-images.githubusercontent.com/77084039/193825924-78130de7-4007-41db-b7ce-4335aea9b27c.png)

Hey everyone 👋 
I got this with 9004 port  `Encountered a problem while trying to connect to mysql: 2003: Can't connect to MySQL server on 'my_host:9004' (60 Operation timed out)`
Any ideas?

```
data_source ch_dwh:
  type: mysql
  connection:
    host: my_host
    port: '9004'
    username: my_user
    password: my_pass
    database: my_db
```

ClickHouse: 22.3.3.44
soda-core: 3.0.16
soda-core-mysql: 3.0.16

**Comment by bvolodarskiy** [comment]
@vijaykiran Hello, could you help here and answer, did you use Cloud version of clickhouse or it was local?
