### ISSUE TITLE
Soda-Core Azure Synapse support

### ISSUE THREAD

**Issue by TimEllens** [sodadata/soda-core#1601]
Hi everyone,

Is Azure Synapse going to be support for Soda-Core? Either from Synapse Spark or SQL Serverless/Dedicated?

Only message I could find is a press release where Azure Synapse is mentioned: https://www.soda.io/press/soda-empowers-data-engineers-with-soda-sql.

**Comment by jmarien** [comment]
SODA-1188

**Comment by benjamin-pirotte** [comment]
Hi @TimEllens , Azure Synapse is one of the next data sources we will add it in the next couple of months.

**Comment by vijaykiran** [comment]
Azure Synapse is supported via SQLServer package: https://docs.soda.io/soda/connect-synapse.html
