### ISSUE TITLE
Schema Check is Unable to Work when Variable is passed

### ISSUE THREAD

**Issue by essayyzed** [sodadata/soda-core#1610]
I am facing an issue when defining variables for my check. The issue is that the variable works fine in all the checks other than `Schema Check`  where is raise the following error:
`"value": [{"columnName": c["name"], "sourceDataType": c["type"]} for c in self.value],
TypeError: 'Undefined' object is not iterable.`

My checks.yml looks like this:
`variables:`
    `table: 'customers'`
`checks for ${table}:`
 ` - schema:`
      `fail:`
        `when required column missing:`
          `- id`
          `- name`
What could be the possible reason for this error.? Or is it a bug related to `variable` usage in `Schema Check`

**Comment by jmarien** [comment]
SODA-1197

**Comment by vijaykiran** [comment]
Closed via #1628

**Comment by ceyhunkerti** [comment]
this issue appears again after the last commit that modifies `schema_query.py`
