### ISSUE TITLE
'valid regex' counts records matching the regex as invalid

### ISSUE THREAD

**Issue by geertvanzoest** [sodadata/soda-core#1626]
**Problem**
With this in my checks.yml:
```
# Check a Dutch postal code to confirm that all values are in valid format
  - invalid_percent("Post Code") < 1%:
      name: Format check - Postcode
      valid regex: "[1-9][0-9][0-9][0-9] [a-zA-Z][a-zA-Z]"
```

I get this result:
```
1/13 checks FAILED:
    Contact in nav
      Format check - Postcode [FAILED]
        check_value: 99.84
        row_count: 24677
        invalid_count: 24637
```

I'm pretty sure that the numbers are exactly the other way around (24637 valid and 40 invalid). When I use a SQL profiler to catch the SQL query that Soda executed, it looks like the regex is being inverted as a condition. So instead of counting the records that do not match the regex as invalid, it counts the records that do match the regex as invalid:
`COUNT(CASE WHEN (NOT ("Post Code" IS NULL) AND NOT (PATINDEX ('%[1-9][0-9][0-9][0-9] [a-zA-Z][a-zA-Z]%' ,"Post Code" ) = 0)) THEN 1 END)
`

**Suspected cause**
This happens because PATINDEX() returns a zero if given pattern isn't found in given string. Soda counts each hit as an invalid record. Therefore, the current expression NOT (PATINDEX ('%yourRegexHere%' ,"yourColumnHere" ) = 0) evaluates to TRUE for each record matching the regex, resulting in an inverted count of valid versus invalid records.

**Steps to reproduce**
1. Have a (SQL Server) table containing at least some values
2. Configure checks.yml with:
```
- invalid_percent("column name") < 1%:
      valid regex: "your regex"
```
3. Run soda scan and you will see valid values counted as invalid

**System**
**OS**: Windows Server 2022, Windows 10 Enterprise 21H2
**Docker version**: 20.10.17
**Soda Core version**: 3.0.10
**Data source type**: Microsoft SQL Server 2019 (15.0.2080.9)

**More about PATINDEX():**
https://learn.microsoft.com/en-us/sql/t-sql/functions/patindex-transact-sql?view=sql-server-ver16

Let me know if I can test anything for you on SQL Server! ✋🏼

**Comment by jmarien** [comment]
SODA-1210

**Comment by m1n0** [comment]
Thanks for reporting and analyzing this @geertvanzoest ! The fix for this one was sitting in our backlog for some time as we had some issues with tests, the fix broke them because of double error which made the tests pass originally and was hard to track down. PR #1669 fixes this one, closing.

**Comment by geertvanzoest** [comment]
Yeah.. I know, right. SQL Server has a real poor regex-implementation. Thanks for looking into it 🚀
