### ISSUE TITLE
= sign in variables does not work

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#1631]
When providing an = as part of a password or similar will not be interpreted correctly since Soda Core will view that as a new variable. It would be great to have a way to escape signs. We have tested with single/double quotes and \ and it did not work. 

Using system variables is a workaround though: https://docs.soda.io/soda-core/configuration.html#provide-credentials-as-system-variables

**Comment by jmarien** [comment]
SODA-1222

**Comment by m1n0** [comment]
This was fixed in [3.0.11](https://github.com/sodadata/soda-core/releases/tag/v3.0.11)
