### ISSUE TITLE
Email validation considers plus signs invalid

### ISSUE THREAD

**Issue by tombriggsallego** [sodadata/soda-core#1662]
If you define a validity check (e.g. invalid_count, invalid_percent) with `valid format: email`, it will flag emails addresses containing plus signs as invalid. This makes things like the very common and very useful real+custom@gmail.com appear invalid. GMail extensions aside though plus signs are generally valid in email addresses.

**Comment by jmarien** [comment]
SODA-1268

**Comment by m1n0** [comment]
This was fixed in [v3.0.13](https://github.com/sodadata/soda-core/releases/tag/v3.0.13)
