### ISSUE TITLE
Bump requests package version

### ISSUE THREAD

**Issue by bjorhn** [sodadata/soda-core#1673]
Would it be possible to bump the requests library to 2.28.1 or higher? I've been getting some rather ugly warnings whenever I run code in the same venv I have soda-core installed in due to requests being outdated. When trying to run `pip3 install --upgrade requests` it says:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
soda-core 3.0.10 requires requests~=2.27.1, but you have requests 2.28.1 which is incompatible.`

**Comment by vijaykiran** [comment]
Fixed - please use 3.0.16 version and re-open if this is still an issue.
