### ISSUE TITLE
change_request: only run printSchema() and df.show() when verbose == true

### ISSUE THREAD

**Issue by jochemvredeveld** [sodadata/soda-core#1696]
**location**
/soda/spark_df/soda/data_sources)/spark_df_data_source.py

            _def test(self, sql: str):
                logging.debug(f"Running SQL query:\n{sql}")
                df = self.connection.spark_session.sql(sqlQuery=sql)
                df.printSchema()
                df.show()

**issue**
we are running soda core programmatically and printing the schema and the df every time a test is run really clusters to output.

**change request**
only run df.printSchema() df.show() when verbose is set to true

**Comment by jmarien** [comment]
SODA-1317

**Comment by jochemvredeveld** [comment]
@m1n0 can I just say that im very impressed that you fixed this issue so quickly, much appreciated!
