### ISSUE TITLE
Profiling issue with Dremio

### ISSUE THREAD

**Issue by albinkjellin** [sodadata/soda-core#1717]
The profiling in Dremio does not work as expected:

This is the SQL being generated:
```
SELECT table_name
FROM information_schema.tables
WHERE table_name not like '%.%'
```

But tables needs to be in quotes according to this:

https://docs.dremio.com/cloud/sql/information-schema/tables/

**Comment by nicodp-leap** [comment]
Having the same problem in our team.

**Comment by vijaykiran** [comment]
Please check with 3.0.16 - it should work now, if not please re-open the issue.

**Comment by nicodp-leap** [comment]
@vijaykiran We are using Soda Cloud version, do we need to update something manually on the agent?
