### ISSUE TITLE
Release 3.0.16

### ISSUE THREAD

**Issue by f0rmiga** [sodadata/soda-core#1734]
@vijaykiran, thanks for aligning the dependencies in https://github.com/sodadata/soda-core/commit/f36ea6bf154c58102d61ee6d1be785c981476b96.

Would it be okay to cut a new release containing it?

**Comment by jmarien** [comment]
SODA-1350

**Comment by vijaykiran** [comment]
Release was scheduled for today and is available now: https://github.com/sodadata/soda-core/releases/tag/v3.0.16

**Comment by f0rmiga** [comment]
Thank you!
