### ISSUE TITLE
Rule Name in Checks file

### ISSUE THREAD

**Issue by sergioroam** [sodadata/soda-core#1761]
Hello there, 

So we are developing a script that is able to extract failed rows. The script create CSV files. We would like that the file name of CSV to be the same we assign into the CHECKS file.

We also want to know the library where this name is located. 

Thank you!

![MicrosoftTeams-image](https://user-images.githubusercontent.com/122491546/211933819-9ebad3b1-5a26-41f9-8ebb-75867ae81185.png)

**Comment by jmarien** [comment]
SODA-1367

**Comment by vijaykiran** [comment]
Hi @sergioroam  Not sure what you mean by the file name - a checks file can contain multiple checks so we can't pick one name of a check as the checks file. The name property you are referring to is shown as a descriptive/user-friendly name in Soda Cloud. 

And as far as the location of name in library  - do you mean location in the code? I don't understand that question.

**Comment by sergioroam** [comment]
Hello 

Okey I get it. Is there a way to do what we want to run with our script?

Referring to your question, yes, we need the location  of the data in the code. 

Thank you!

**Comment by vijaykiran** [comment]
@sergioroam  if you are using custom Sampler (as shown here https://docs.soda.io/soda-cl/failed-rows-checks.html#configure-a-failed-row-sampler) you can get the check name from `SampleContext` object  (see https://github.com/sodadata/soda-core/blob/94bdcc217b04f5fa9d84c416dc1a4307811d5e71/soda/core/soda/sampler/sample_context.py#L23)
