### ISSUE TITLE
Custom sql comparison between 2 data source

### ISSUE THREAD

**Issue by sivankumar86** [sodadata/soda-core#1788]
Usecase:
    We have tables with incremental numeric primary key and I want to run comparison between src and destination based on max primary key. 

Example, 

 Find the max_value : 

     val max_id=s"select max(${pkey}) from ${sf_table}"

MSSQL:
    select  * from   mssql_table  where ${pkey} <= ${max_id}

Snowflake:
        select *  from   snowflake_table  where ${pkey} <= ${max_id}

check in Snowflake:
     row_count is same as MSSQL

Is it possible to achieve above condition in soda ?

**Comment by jmarien** [comment]
SODA-1438

**Comment by m1n0** [comment]
[Reconciliation checks](https://docs.soda.io/soda-cl/recon.html) are a very powerful way to do schema/metric/row comparison across datasources and datasets and are part of our commercial Soda Library offering.
