### ISSUE TITLE
cross dataset in custom check 

### ISSUE THREAD

**Issue by sivankumar86** [sodadata/soda-core#1795]
I want to implement custom thresh hold for row count with cross dataset (mssql table vs snowflake table) but, I am not sure how to refer cross dataset in custom query as in is not working 

https://docs.soda.io/soda-cl/check-templates.html#set-an-acceptable-threshold-for-row-count-delta

`
checks for snowflake:
  - row_delta > 10:
      row_count : 
      row_delta query: |
        with table1 as (
          select count(*) as table_1_rows from  stg_zmdb_account
        ),
        table2 as (
          select count(*) as table_2_rows from account in mssql
        ),
        intermediate as (
          select
            (select table_1_rows from table1) as table_1_rows,
            (select table_2_rows from table2) as table_2_rows
        ),
        difference_calculation as (
          select
            ABS( table_1_rows - table_2_rows)
            as row_delta
          from intermediate
        )
        select
          row_delta
        from difference_calculation

`

**Comment by jmarien** [comment]
SODA-1440

**Comment by m1n0** [comment]
[Reconciliation checks](https://docs.soda.io/soda-cl/recon.html) are a very powerful way to do metric comparison across datasources and datasets and are part of our commercial Soda Library offering.
