### ISSUE TITLE
get_scan_results['metrics'] to include expected value as well

### ISSUE THREAD

**Issue by nikolaPlume** [sodadata/soda-core#1817]
`soda.get_scan_results()` returns a lot of valuable information that can be easily reused in order to represent actual results.
While `'checks'` contains information about check definition and it's results, `'metrics'` gives info about the actually obtained metric's value. What is missing is the **expected** metric **value**.

```
 'metrics': [
             {'dataSourceName': 'spark_df',
              'identity': 'metric-spark_df-table1-column1-missing_count',
              'metricName': 'missing_count',
              'value': 0},
             {'dataSourceName': 'spark_df',
              'identity': 'metric-spark_df-table1-row_count-5d082c52',
              'metricName': 'row_count',
              'value': 45},
             {'dataSourceName': 'spark_df',
              'identity': 'metric-spark_df-table1-invalid_count-8c252c04',
              'metricName': 'invalid_count',
              'value': 0}]
```

So it's easy to get information about the observed values for those 3 metrics (0, 45, 0), and also about the check_result (`'outcome': 'pass'`), but we do not have information about the **expected value** (is it 0, 5, 100).
The only way it to parse it from the name section `'name': 'row_count > 0'` however, it would be nice to have it somewhere in the scan_results dictionary (either in 'metrics' or 'checks').

**Comment by jmarien** [comment]
SODA-1456

**Comment by benjamin-pirotte** [comment]
Would it be a valid alternative to expose the expected value (I think we are talking about the check threshold here, right?) as part of the check object instead? Currently, I think we only expose it in the definition property but it would be difficult to parse to extract it.

**Comment by m1n0** [comment]
indeed, exposing check threshold would make sense - would that help with your use case @nikolaPlume?

**Comment by nikolaPlume** [comment]
@m1n0 Yes it would be good.
Thanks

**Comment by m1n0** [comment]
https://github.com/sodadata/soda-core/pull/1939 adds diagnostics (including thresholds) to scan result dict
