### ISSUE TITLE
Compare 2 datasets (tables)

### ISSUE THREAD

**Issue by NagarajG05** [sodadata/soda-core#1828]
Hi,

Is there an inbuilt check to compare 2 tables(data source) row by row? 

I tried the below custom check with custom SQL and its working but looking inbuilt if any

```
checks for d_plnt:
  - ds_compare = 0:
       ds_compare query :
         with q1 as (
         select *  FROM source_table
         except
         select *  FROM target_table
         )
         select count(*) from q1
```

**Comment by jmarien** [comment]
SODA-1462

**Comment by benjamin-pirotte** [comment]
Hi @NagarajG05 , we don't have inbuilt checks for this use case yet. But I added it to our backlog and we will look into it. Thanks for your feedback!

**Comment by m1n0** [comment]
[Reconciliation checks](https://docs.soda.io/soda-cl/recon.html) are a very powerful way to do schema/metric/row comparison across datasources and datasets and are part of our commercial Soda Library offering.
