### ISSUE TITLE
Perform the computation of categorical bins in SQL rather than in python

### ISSUE THREAD

**Issue by soapergem** [sodadata/soda-core#1845]
Following up on [a Slack conversation](https://soda-community.slack.com/archives/C01HKMV241L/p1678415610882849) we had on DRO generation, we have run into an issue where trying to generate DRO config for a large dataset with the CLI eats up all of our system memory and ultimately never succeeds. One of the suggestions made was to perform a GROUP BY query in SQL rather than doing everything locally with Pandas. This seems more ideal so I'm creating this issue to track things, possible pull request to follow.

**Comment by jmarien** [comment]
SODA-1525

**Comment by bastienboutonnet** [comment]
Hi @soapergem great timing! We actually just planned to work on this issue internally as of Tuesday, but I did not have a chance to update back the slack thread yet.

I expect my team will have something for at least the most common cloud databases + postgres working and ready for inclusion in the next tag of soda-core.

**Comment by m1n0** [comment]
This has been released in [v3.0.32 ](https://github.com/sodadata/soda-core/releases/tag/v3.0.32)
