### ISSUE TITLE
Support DBT Core 1.4 version manifest files

### ISSUE THREAD

**Issue by ashishmgofficial** [sodadata/soda-core#1870]
Soda is unable to parse the manifest json files while trying to integrate dbt test results to soda cloud. I think this is because `1.4` version `dbt-core` uses `v8` manifest while the soda supports only `v6` manifest of dbt as stated [here](https://github.com/sodadata/soda-core/blob/27463ad93ddbc11700e619ef70c35ca4f4865b52/soda/dbt/soda/cloud/dbt.py#LL302C8-L302C39), which is very old and also the dbt core version supported is `dbt-core==1.3.x`

So, its not able to parse the manifest files generated by dbt versions > 1.3.x

**Comment by jmarien** [comment]
SODA-1732

**Comment by benjamin-pirotte** [comment]
Hi, thank you for your request. We will add support for 1.4 and 1.5 in the course of the month of June. Thank you!

**Comment by m1n0** [comment]
dbt 1.5 and 1.6 are currently supported in Soda Library (the commercial offering). There are currently no plans do change the Soda Core implementation since ingesting dbt tests works with Soda Cloud only anyway.
