### ISSUE TITLE
MS SQL Server sources table- and column handling issue

### ISSUE THREAD

**Issue by David-DataKnowledge** [sodadata/soda-core#1911]
As discussed on Slack with @bastienboutonnet I would like to report an issue in Soda Core concerning the handling of spaces in table or column names. Or the possibility to escape names with spaces in it. Given the fact that Microsoft SQL Server is very flexible while working from SQL Server Management Studio, I have tried a variety of escape characters. To keep this report clean I decided to report the following 2 configurations as an example:

1.  Soda Cloud configuration with the universal escape in MS SQL: the "[" and "]" 
2.  Soda Cloud configuration without any escape characters according to the documentation.

1:
```
discover datasets:
  datasets:
    - include [Dummy Name]

profile columns:
  columns:
    - include [Dummy Name].%

automated monitoring:
  datasets:
    - include [Dummy Name]
```
[Config1Log.txt](https://github.com/sodadata/soda-core/files/12078713/Config1Log.txt)

2:
```
discover datasets:
  datasets:
    - include Dummy Name

profile columns:
  columns:
    - include Dummy Name.%

automated monitoring:
  datasets:
    - include Dummy Name
```
[Config2Log.txt](https://github.com/sodadata/soda-core/files/12078714/Config2Log.txt)

Also the following issue I have in Soda Cloud seems to be connected to this (quoted from Slack):

Maybe it is a user-error but because of the space in the table name of the MS SQL, data source, I have to wrap the table name with double-quotes in the agreement. Otherwise I get an invalid header:
`Invalid section header "checks for Dummy Name"`

Once wrapped, the execution of the contract splits the dataset into two. One for the data source and one for the agreement (see attached picture).
The first line of the agreement:
`checks for "Dummy Name":`

Is there an escape character for this, so that the cloud interface shows all information in one dataset?
![image](https://github.com/sodadata/soda-core/assets/132888330/16a89a45-f139-4c6b-b7a2-34f1d3602f4c)

**Comment by m1n0** [comment]
This was resolved in #1959 , released in [v3.0.54](https://github.com/sodadata/soda-core/releases/tag/v3.0.54), closing
