### ISSUE TITLE
pandas dask tutorial warnings/errors

### ISSUE THREAD

**Issue by rolandrmgservices** [sodadata/soda-core#1912]
Thanks for open sourcing this!

I was working on the example at:
[pandas_dask_tutorial.ipynb](https://github.com/sodadata/soda-core/blob/main/examples/pandas_dask_tutorial.ipynb)

In this Colab: https://colab.research.google.com/drive/1hDOqNY83GDBEfQaM14nKl8VKI-A-QSVD?usp=sharing

But ran into issues:

![image](https://github.com/sodadata/soda-core/assets/97845453/1cc2c8b3-dc3d-40f5-ac18-976c1175fb4e)

I'm unsure if this is the intended behavior?

**Comment by baturayo** [comment]
Hi @rolandrmgservices,

Thanks lot for pointing the issue, I added `print(scan.get_logs_text())` to print the scan results from soda_core into your colab notebook. I saw no error in soda-core and I saw the expected results. The warning seems to be common from dask-sql which uses arrow-datafusion. I'll further have a look why it happens. However, it doesn't have an impact on soda-core.
