### ISSUE TITLE
Review added at repo-reviews.github.io

### ISSUE THREAD

**Issue by ras44** [sodadata/soda-core#1917]
### Thank you for building **soda-core**!

@ras44 created a review titled:

*Promising library, quickstart confusion*

on [repo-reviews.github.io](https://repo-reviews.github.io) to share their experience using **soda-core**.

[link to review](https://repo-reviews.github.io//reviews/2023-07-21_ras44_sodadata_soda-core)

If you would like to help your super-users share their experiences using your repo, add a [badge](https://github.com/repo-reviews/repo-reviews.github.io#add-badges) to your README.md.

We hope that sharing these experiences helps your users **increase their productivity**.

--
Please be kind,
I’m a human!

**Comment by jmarien** [comment]
SODA-1794
