### ISSUE TITLE
SodaCore 3.0.48 is not compatible with Airflow 2.7

### ISSUE THREAD

**Issue by nathadfield** [sodadata/soda-core#1928]
[Apache Airflow 2.7](https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#airflow-2-7-0-2023-08-14) has just been released but it looks like it not not possible to install the latest version of Soda Core due to a conflict with `opentelemetry-api`.

```
ERROR: Cannot install apache-airflow==2.7.0 and soda-core==3.0.48 because these package versions have conflicting dependencies.

The conflict is caused by:
    apache-airflow 2.7.0 depends on opentelemetry-api==1.15.0
    soda-core 3.0.48 depends on opentelemetry-api~=1.16.0
```

**Comment by jmarien** [comment]
SODA-1811

**Comment by nathadfield** [comment]
Going to close as this is really an issue with Airflow who are looking to correct this in the next version.
