### ISSUE TITLE
Error connection with SQL and param string Trusted_Connection=True

### ISSUE THREAD

**Issue by rodrigomartinez1302** [sodadata/soda-core#1934]
Hi everyone, I found an issue when building the string connection with sql on the module:  sqlserver_data_source.py

When the connection is trusted, you dont need user and pass, so the solution could be:
(the last two lines were added)

self.connection = pyodbc.connect(
                ("Trusted_Connection=YES;" if self.trusted_connection else "")
                + ("TrustServerCertificate=YES;" if self.trust_server_certificate else "")
                + ("Encrypt=YES;" if self.encrypt else "")
                + "DRIVER={"
                + self.driver
                + "};SERVER="
                + self.host
                + ","
                + str(self.port)
                + ";DATABASE="
                + self.database
                **+ (";UID=" + self.username  if not self.trusted_connection else "")
                + (";PWD=" + self.password  if not self.trusted_connection else "")**
            )

Many thanks guys for the job done, i am starting to use it and i like it :)

**Comment by tools-soda** [comment]
SAS-2143

**Comment by vijaykiran** [comment]
Thank you for the report @rodrigomartinez1302 ! Would you like to open a PR with the fix? I'll be happy to merge it ASAP.

**Comment by tinkujv** [comment]
Hi, Is this issue fixed ?

**Comment by m1n0** [comment]
Not yet, would you be able to open a PR for this @rodrigomartinez1302 ?

**Comment by sdebruyn** [comment]
Fixed this in #2160
