### ISSUE TITLE
Schema checks not working for DuckDB connection

### ISSUE THREAD

**Issue by pauliehyland** [sodadata/soda-core#1940]
Hi,

When using Soda Core and connecting to DuckDB, schema checks don't seem to be supported. Could this please be investigated?

Thanks,

Paul

**Comment by tools-soda** [comment]
SAS-2199

**Comment by m1n0** [comment]
Hi @pauliehyland ! Schema checks are supported in duckdb, could you please elaborate? Ideally post your config, check file and console logs with `-V` option (redacted of any sensitive info)

**Comment by pauliehyland** [comment]
Thanks @m1n0, I've reached out to the users who I logged this issue on behalf of and they're going to double-check and update here if still an issue. Thanks!

**Comment by pauliehyland** [comment]
Hi @m1n0, this can actually be closed as it's working - our issue was that we weren't adding the schema_name option. Thanks a lot for your time.
