### ISSUE TITLE
Antlr doesn't parse composite threshold in freshness check

### ISSUE THREAD

**Issue by Quasilol** [sodadata/soda-core#1945]
When trying to use composite threshold in freshness check, antlr doesn't recognize threshold like '1d1h' as a freshness threshold

For example:
```
checks for {table_name}:
    - freshness(ts) < 1d9h
```
Return error:
`ERROR    soda.scan:log.py:101 [17:56:29] Invalid check "freshness(ts) < 1d9h": extraneous input 'd9h' expecting <EOF>`

**Comment by tools-soda** [comment]
SAS-2318

**Comment by m1n0** [comment]
This is now fixed in #1957 and will be released in the next release, thanks for reporting!
