### ISSUE TITLE
Regex pattern issue for (at least) SQL Server data source

### ISSUE THREAD

**Issue by chuwangBA** [sodadata/soda-core#1955]
SODA core has an issue while parsing the regex format:

if I want exact 9 digit value in my column, I will write like this
```
- invalid_count(account_number) = 0:
      valid regex: '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
```
but SODA renders it to

`PATINDEX('%[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]%', YourColumn)`

the % is unwanted, because it will pass for > 9 digits value (like if my account_number get 10 digit, it wont fail)

SQL Serve also doesn't support format like [0-9]{9} like python regex

From SQL Server official doc: https://learn.microsoft.com/en-us/sql/t-sql/functions/patindex-transact-sql?view=sql-server-ver16
`however, the % character must come before and follow pattern (except when you search for first or last characters).`

I would propose to let users decide when and how they wanna add '%' to their 'valid regex' section

**Comment by tools-soda** [comment]
SAS-2407
