### ISSUE TITLE
Datahub intergration

### ISSUE THREAD

**Issue by KulykDmytro** [sodadata/soda-core#1969]
Are there any plans to have integration with Datahub?
We are thinking about our custom ingestor for a couple of last months, and will be great in case you have any plans on this to make it native.

**Comment by tools-soda** [comment]
SAS-2493

**Comment by bastienboutonnet** [comment]
Hi there @KulykDmytro 

Thanks for reaching out with your question about Datahub integration – it's always exciting to hear what's on our users' minds!

So, here's the scoop: We love making things mesh together, especially when it comes to data catalogs. Our approach? We do this via our Cloud product, which exposes a Catalog API meant for catalog devs/vendors to build the integration on top of the data we expose through this API.

Now, let's talk Datahub. They're aware of our Catalog API. If they decide to tie the knot with our platform, we're all set to help them out.

If you're considering using our Cloud product and are also a Datahub client, we recommend reaching out to Datahub to express your interest in this integration.

Just a heads-up: Our soda-core product likes to keep things simple. It doesn't venture into building direct catalog integrations. But, we're all about supporting you through our Cloud product.

Feel free to reach out if you've got more questions or ideas. We're all ears and ready to assist! I'll leave this issue open for a bit just in case there's some follow up, if not I'll consider it closed.
