### ISSUE TITLE
MySQL library installation Windows bluescreen

### ISSUE THREAD

**Issue by JorritMaesDatashift** [sodadata/soda-core#1972]
Hello everyone,

Whilst installing the soda library for mysql following the instructions on this page: https://docs.soda.io/soda-library/install.html my pc bluescreens. I have however succeeded to install soda core whilst refering to these instructions: https://github.com/sodadata/soda-core/blob/main/docs/installation.md .

My environment:
 - windows 11
 - pip 23.2.1
 - Python 3.12.0
 - running mysql using Xampp 8.2.12 (however I have tried installing it while Xampp was not yet installed with the same result
 
Commands ran: 
py -m venv .venv
.\.venv\Scripts\activate
pip install -i https://pypi.cloud.soda.io soda-mysql

**Comment by dirkgroenen** [comment]
Hi @JorritMaesDatashift! This sounds like quite a specific issue that I haven't heard to happen before and is likely very much related to your local setup.  We might be able to help you if you share the event logs of your bsod.

**Comment by m1n0** [comment]
hi @JorritMaesDatashift  - indeed, any more info, especially logs - would be helpful here.

**Comment by JorritMaesDatashift** [comment]
[120723-12859-01.dmp](https://github.com/sodadata/soda-core/files/13645191/120723-12859-01.dmp)
Hello, thank you very much for the help I've have included my dump file in thid comment.

**Comment by m1n0** [comment]
Happy to hear that!
