### ISSUE TITLE
Support nested columns

### ISSUE THREAD

**Issue by jochenchrist** [sodadata/soda-core#1979]
So far, I found no way to define schema checks for nested columns, e.g., tables using [composite types](https://www.postgresql.org/docs/current/rowtypes.html).

**Example with PostgreSQL**

```
CREATE TYPE address_type AS (
  street VARCHAR(255),
  city   VARCHAR(100),
  state  VARCHAR(100),
  zip    VARCHAR(20)
);
```

```
CREATE TABLE orders (
  id SERIAL PRIMARY KEY,
  order_date DATE NOT NULL,
  customer_name VARCHAR(100) NOT NULL,
  address address_type NOT NULL
);
```

```
INSERT INTO orders (order_date, customer_name, address)
VALUES ('2023-01-01', 'John Doe', ROW('1234 Elm Street', 'Springfield', 'IL', '62704'));
```

**checks.yml**

(does not work)

```
checks for orders:
  - schema:
      name: Confirm that nested columns are present
      fail:
        when required column missing:
          - customer_name 
          - (address).city
```

Fails with
>AssertionError: Check results failed: 
[schema] FAIL (fail_missing_column_names = [(address).city], schema_measured = [id integer, order_date date, customer_name character varying, address USER-DEFINED])

**Comment by tools-soda** [comment]
SAS-2615

**Comment by m1n0** [comment]
Hi @jochenchrist! This is a known limitation - nested fields have limited support - they work on most built-in checks but not the schema check which requires more nuanced handling. Improving this is on our longer term backlog, so I will close this issue now. Keep an eye on our release notes for when this changes.
