### ISSUE TITLE
Passwords with `:` are invalidating the config files

### ISSUE THREAD

**Issue by vinod901** [sodadata/soda-core#2015]
- If a password happens to have a `:` in it like `{xxxxx*:x<,xxxx`

![image](https://github.com/sodadata/soda-core/assets/58871377/97295028-de71-415f-9e2e-8408ae3de51a)

- If we wrap the password in `"`'s . like `password: "{xxxxx*:x<,xxxx"`

![image](https://github.com/sodadata/soda-core/assets/58871377/74122335-8f7b-4e46-905b-4c1c00a85f63)

I have also tried some alternatives as well!
None of the worked like using a `|` and  `>`.

**Comment by tools-soda** [comment]
SAS-2839

**Comment by m1n0** [comment]
Fixed by #2018
