### ISSUE TITLE
Character `#` in filter breaks sql generation

### ISSUE THREAD

**Issue by Quasilol** [sodadata/soda-core#2019]
When character `#` is used in filter, it breaks generation of sql.

For example:
```
checks for {table_name}:
    - sum(decimal_value) > 0:
        filter: category = 'Active, #'
```
Return error
`DEBUG  |     unterminated quoted string at or near "'Active, THEN decimal_value END)`
`    LINE 2:   SUM(CASE WHEN category = 'Active, THEN decimal_value END) `

My guess is character `#` is thrown away during Antlr's parsing.

**Comment by tools-soda** [comment]
SAS-2853

**Comment by m1n0** [comment]
Surrounding the value in double quotes solves the problem i.e. `filter: "category = 'Active, #'"`
