### ISSUE TITLE
Change argument name in set_scan_results_file method

### ISSUE THREAD

**Issue by ozgenbaris1** [sodadata/soda-core#2040]
I think both the function and its argument having the same name can make confusions here. I'm suggesting to change the argument name to something like `scan_results_file`.

https://github.com/sodadata/soda-core/blob/a1a200862e79af4f01847241133d88a1260568b8/soda/core/soda/scan.py#L127-L128

**Comment by tools-soda** [comment]
SAS-3088

**Comment by m1n0** [comment]
hi, sure that makes sense, could you open a PR please?

**Comment by ozgenbaris1** [comment]
@m1n0 hi, 

here you go https://github.com/sodadata/soda-core/pull/2047
