### ISSUE TITLE
Update OpenTelemetry Dependencies

### ISSUE THREAD

**Issue by DGuhr** [sodadata/soda-core#2041]
Hi 👋  is an update of the [opentelemetry dependencies ](https://github.com/sodadata/soda-core/blob/a1a200862e79af4f01847241133d88a1260568b8/soda/core/setup.py#L17-L18) planned, if I may ask?

Context:
We wanted to add OTEL to our cli, that also uses soda ([datacontract-cli](https://github.com/datacontract/cli)) and due to the transitive dependency it wasn't possible to update to the latest version of these dependencies without breaking compatibility - at least if I understood the pip output correctly (relatively new to python). 

So, it'd be nice to not be blocked here anymore. If it is not on your plate, I might have some time next week to investigate this and provide a PR. For that it'd be nice to know how to run tests, etc. - but I just saw that you have a Contributing.MD 👍 - if that suffices, I might take a look.

**Comment by tools-soda** [comment]
SAS-3107

**Comment by m1n0** [comment]
Good timing, this was on our table for a couple of days now, linked PR opens up the option to upgrade OT.

**Comment by m1n0** [comment]
[3.3.1](https://github.com/sodadata/soda-core/releases/tag/v3.3.1) release allows OT to be bumped all the way to 1.22

**Comment by DGuhr** [comment]
Thanks! 👍
