### ISSUE TITLE
Add support failed rows query in user defined metric check 

### ISSUE THREAD

**Issue by sagarwal144** [sodadata/soda-core#2044]
Currently, we don't have a way to specify the failed row query in the user defined metric. So when the user defined metric check fails, we are not able to collect the sample failed rows in either SODA Cloud or CustomSampler. This issue proposes to add failed row query section in the user defined metric as follows 
```
- test_metric_query = 0:
      test_metric_query query: |
        SELECT count(*)
        FROM group_subs where start_date > end_date
      fail query: |
        SELECT id, start_date, end_date
        FROM group_subs where start_date > end_date
        LIMIT 5
```

**Comment by tools-soda** [comment]
SAS-3109

**Comment by benjamin-pirotte** [comment]
Hi, thanks for your request! This feature will added early May.

**Comment by sagarwal144** [comment]
Thanks for adding this feature!

**Comment by m1n0** [comment]
Added in #2089
