### ISSUE TITLE
Contract API docs update

### ISSUE THREAD

**Issue by tombaeyens** [sodadata/soda-core#2057]
Decide on introducing the ContractVerificationResult class.
Switch docs to ContractVerification API.

**Comment by tools-soda** [comment]
SAS-3251

**Comment by tombaeyens** [comment]
Updated SQL metric expression docs (column and dataset level) : https://deploy-preview-768--jovial-piroshki-65ff4d.netlify.app/soda/data-contracts-checks#sql-metric-expression

Updated SQL metric query docs (column and dataset level) : https://deploy-preview-768--jovial-piroshki-65ff4d.netlify.app/soda/data-contracts-checks#sql-metric-query

Both of these check types require a `metric` property.
