### ISSUE TITLE
Issue connecting to db2 from soda-core

### ISSUE THREAD

**Issue by 4rahulae** [sodadata/soda-core#2062]
Hi Soda team,

I'm having issues connecting to db2 from soda-core .

I'm using the current version of soda-core which is 3.3.1 and the soda-core-db2 version is 3.3.1.

The only work around that works right now is by adding below changes to db2_data_source.py and then adding security as one of the config parameter when setting or configuring db2 connection.

db2 config example:
data_source ibm_db2: 

  type: db2   

  host: {host}

  port: {port}

  username: {username} 

  password: {password}

  database: {database}

  schema: {schema}
  
  security: SSL

here are the changes needed in the db2_data_source.py file :

add this in line number 68 : self.verify_ssl = data_source_properties.get("security")

in line number 72 add security as part of the connection string:  conn_str = (
            f"DATABASE={self.database};HOSTNAME={self.host};PORT={self.port};UID={self.username};PWD={self.password};SECURITY={self.verify_ssl}"
        )

Just wondering if you can please add this change as part of the soda-core release and how soon can you add this

**Comment by tools-soda** [comment]
SAS-3277

**Comment by bastienboutonnet** [comment]
Hi @4rahulae thanks for looking into it and researching the solution. I think the best route might be to open a PR and we'll gladly merge it/support you through merging it.

**Comment by 4rahulae** [comment]
here is the PR link below:

https://github.com/sodadata/soda-core/pull/2063

How soon can this change be added to the soda-core release?
