### ISSUE TITLE
not able to install in databricks enviornment

### ISSUE THREAD

**Issue by rohan-databricks** [sodadata/soda-core#2068]
I am getting below error while trying to install soda on databricks dbr 13.3

× python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [30 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.linux-x86_64-cpython-310 creating build/lib.linux-x86_64-cpython-310/sasl copying sasl/__init__.py -> build/lib.linux-x86_64-cpython-310/sasl running egg_info writing sasl.egg-info/PKG-INFO writing dependency_links to sasl.egg-info/dependency_links.txt writing requirements to sasl.egg-info/requires.txt writing top-level names to sasl.egg-info/top_level.txt reading manifest file 'sasl.egg-info/SOURCES.txt' reading manifest template 'MANIFEST.in' adding license file 'LICENSE.txt' writing manifest file 'sasl.egg-info/SOURCES.txt' copying sasl/saslwrapper.cpp -> build/lib.linux-x86_64-cpython-310/sasl copying sasl/saslwrapper.h -> build/lib.linux-x86_64-cpython-310/sasl copying sasl/saslwrapper.pyx -> build/lib.linux-x86_64-cpython-310/sasl running build_ext building 'sasl.saslwrapper' extension creating build/temp.linux-x86_64-cpython-310 creating build/temp.linux-x86_64-cpython-310/sasl x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Isasl -I/local_disk0/.ephemeral_nfs/envs/pythonEnv-004b2974-178b-43d4-98b2-b5d8481a8b7d/include -I/usr/include/python3.10 -c sasl/saslwrapper.cpp -o build/temp.linux-x86_64-cpython-310/sasl/saslwrapper.o In file included from sasl/saslwrapper.cpp:629: sasl/saslwrapper.h:22:10: fatal error: sasl/sasl.h: No such file or directory 22 | #include <sasl/sasl.h> | ^~~~~~~~~~~~~ compilation terminated. error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1 [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for sasl Running setup.py clean for sasl

**Comment by tools-soda** [comment]
SAS-3323

**Comment by m1n0** [comment]
Hi, as per our [docs](https://docs.soda.io/soda/connect-spark.html#connect-to-spark-dataframes), you need to install libsasl2-dev
