### ISSUE TITLE
Invalid configuration header: expected "data_source {data source name}"

### ISSUE THREAD

**Issue by andreyolv** [sodadata/soda-core#2072]
pip install soda-core
pip install soda-core-postgres

configuration.yml
```
data_source my_postgres:
  type: postgres
  connection:
    host: localhost
    username: postgres
    password: postgres123
  database: postgres
  schema: transactional
```

Postgres Table:
![image](https://github.com/sodadata/soda-core/assets/49295662/adb18432-8fa6-45c9-a248-de7255a887d2)

checks.yml
```
checks for d_month:
- schema:
    fail:
      when required column missing:
        - month_id
        - action_month
- missing_count(action_month) = 0:
    name: All products have a key

```

soda test-connection -c configuration.yml -d my_postgres
```
[10:26:22] Soda Core 3.3.3
Successfully connected to 'my_postgres'.
Connection 'my_postgres' is valid.
```

soda scan -c configuration.yml -d my_postgres -c checks.yml -V
```
[10:26:53] Soda Core 3.3.3
[10:26:53] Reading configuration file "configuration.yml"
[10:26:53] Reading configuration file "checks.yml"
[10:26:53] Invalid configuration header: expected "data_source {data source name}".
  +-> line=None,col=None in checks.yml
[10:26:53] No checks file specified
[10:26:53] Scan execution starts
[10:26:53] Scan summary:
[10:26:53] No valid checks found, 0 checks evaluated.
[10:26:53] 1 errors.
[10:26:53] Oops! 1 error. 0 failures. 0 warnings. 0 pass.
ERRORS:
[10:26:53] Invalid configuration header: expected "data_source {data source name}".
  +-> line=None,col=None in checks.yml
```

What am I doing wrong?
It would be great if the documentation could have simple, clear end-to-end examples like this

**Comment by tools-soda** [comment]
SAS-3356

**Comment by m1n0** [comment]
hi, you are passing in the checks file as a config file using the `-c` parameter. Check files need to be passed in as a positional argument, with no prefix, i.e 
```
soda scan -c configuration.yml -d my_postgres checks.yml -V
```
I am not sure what exactly are you missing from docs, our online docs have multiple examples, e.g. [Take a sip of Soda](https://docs.soda.io/soda/quick-start-sip.html) and even the open source docs have complete docs and examples like [this one](https://github.com/sodadata/soda-core/blob/main/examples/postgres_example.md).
