### ISSUE TITLE
Analyze compatibility of check identities across sodacl and contracts

### ISSUE THREAD

**Issue by tombaeyens** [sodadata/soda-core#2120]
I think we should discuss this so we can show how we are going to become better at syncing with other tools (like was the case for Atlan).  And how we will make it more transparent when checks can preserve their history.

Currently, in the translation to SodaCL, check identities are explicit in contracts are a consistent hash of 
* data source name
* database name
* schema name
* dataset name

Analyse and describe how identities will work in the future so others can comment.

Consider if these identity properties themselves have to be passed to Soda Cloud as well.

**Comment by tools-soda** [comment]
SAS-3793

**Comment by dirkgroenen** [comment]
Moved https://sodadata.slite.com/api/s/dqaEPsDsk4TUg1/Check-identities-compatabillity-across-SodaCL-and-Contracts
