### ISSUE TITLE
Contract reuse mechanism

### ISSUE THREAD

**Issue by tombaeyens** [sodadata/soda-core#2169]
The reason why I think we should sync on these potential solutions is that some features might be solved with one of these reuse mechanisms or with other approaches.  Like a number of scaling features may be done with reuse or with tooling.  It's important we all understand these alternatives

Todo: Explore and clarify options

* Include on YAML level
* Include on logical contract level
* A form of contract inheritance
* Templates

**Comment by tools-soda** [comment]
CLOUD-8494

**Comment by dirkgroenen** [comment]
https://sodadata.slite.com/api/s/IjFIGp9n-aZz3-/Scaling-re-using-YAML-declarations-in-Contracts
