### ISSUE TITLE
Define migration strategy

### ISSUE THREAD

**Issue by tombaeyens** [sodadata/soda-core#2171]
https://docs.google.com/presentation/d/1_kulucadChSlQwxr1j5loK_oZ3IqtsltTQrxdJuArTU/edit#slide=id.p

proposal
1) YAML editor coupled to python API &  airflow operator
2) YAML + WYSIWYG editor coupled to python API &  airflow operator
3) 1 click contract generation
4) failed rows
5) git sync
6) scalability features

**Comment by tools-soda** [comment]
CLOUD-8503
