### ISSUE TITLE
Consumer discovery flow in Soda vs catalog integration

### ISSUE THREAD

**Issue by tombaeyens** [sodadata/soda-core#2172]
I think we need to clarify what and how we build out consumer use cases in soda itself to offer and show value to anyone vs aligning and integrating with catalogs which is our strategy.

We need to work out 2 flows: 
1) An integrated consumer flow that shows how consumers can find data and assess the contract API for data in Soda.
2) Show how we integrate with catalogs (and identify the common patterns of catalog integrations and support those via API)

**Comment by tools-soda** [comment]
CLOUD-8508
